name: Build and Publish Docs to GitHub Pages

on:
  release:
    types:
      - created
  push:
    branches: [ "main" ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Generate Dokka Site
        run: |-
          mvn clean compile site && \
          mkdir -p target/docs && \
          cp -R target/dokka target/docs/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
